// --- Day 7: Laboratories ---
// You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

// Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

// Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

// Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

// You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

// For example:

// .......S.......
// ...............
// .......^.......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

// .......S.......
// .......|.......
// .......^.......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// At that point, the original beam stops, and two new beams are emitted from the splitter:

// .......S.......
// .......|.......
// ......|^|......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// Those beams continue downward until they reach more splitters:

// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// .....|^|^|.....
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// This process continues until all of the tachyon beams reach a splitter or exit the manifold:

// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// .....|^|^|.....
// .....|.|.|.....
// ....|^|^|^|....
// ....|.|.|.|....
// ...|^|^|||^|...
// ...|.|.|||.|...
// ..|^|^|||^|^|..
// ..|.|.|||.|.|..
// .|^|||^||.||^|.
// .|.|||.||.||.|.
// |^|^|^|^|^|||^|
// |.|.|.|.|.|||.|
// To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

// Analyze your manifold diagram. How many times will the beam be split?

// --- Part Two ---
// With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

// With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

// Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

// To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

// In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

// .......S.......
// .......|.......
// ......|^.......
// ......|........
// .....|^.^......
// .....|.........
// ....|^.^.^.....
// ....|..........
// ...|^.^...^....
// ...|...........
// ..|^.^...^.^...
// ..|............
// .|^...^.....^..
// .|.............
// |^.^.^.^.^...^.
// |..............
// Or, there's the timeline where the particle alternated going left and right at each splitter:

// .......S.......
// .......|.......
// ......|^.......
// ......|........
// ......^|^......
// .......|.......
// .....^|^.^.....
// ......|........
// ....^.^|..^....
// .......|.......
// ...^.^.|.^.^...
// .......|.......
// ..^...^|....^..
// .......|.......
// .^.^.^|^.^...^.
// ......|........
// Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

// .......S.......
// .......|.......
// ......|^.......
// ......|........
// .....|^.^......
// .....|.........
// ....|^.^.^.....
// ....|..........
// ....^|^...^....
// .....|.........
// ...^.^|..^.^...
// ......|........
// ..^..|^.....^..
// .....|.........
// .^.^.^|^.^...^.
// ......|........
// In this example, in total, the particle ends up on 40 different timelines.

// Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?

const std = @import("std");

pub fn day7_p2(self: anytype) !void {
    const f = try std.fs.cwd().openFile("inputs/day7/input.txt", .{});
    defer f.close();
    var buf: [65536]u8 = undefined;
    var board: std.ArrayList(u8) = std.ArrayList(u8).init(self.allocator);
    var w: usize = 0;
    var h: usize = 0;
    var start_point: usize = 0;
    defer board.deinit();
    while (try f.reader().readUntilDelimiterOrEof(&buf, '\n')) |unfiltered| {
        var line = unfiltered;
        if (std.mem.indexOfScalar(u8, unfiltered, '\r')) |indx| {
            line = unfiltered[0..indx];
        }
        if (line.len == 0) continue;
        if (std.mem.indexOfScalar(u8, line, 'S')) |indx| {
            start_point = indx;
        }
        for (line) |c| {
            try board.append(c);
        }
        h += 1;
        w = line.len;
    }
    //print_board(board, w, h);
    dp = std.AutoHashMap(Point, usize).init(self.allocator);
    defer dp.deinit();
    const timelines = try dfs_trace_beam(board, w, h, .{
        .x = start_point,
        .y = 0,
    });
    std.debug.print("{d} timelines.\n", .{timelines});
}

pub const Point = struct {
    x: usize,
    y: usize,
};

var dp: std.AutoHashMap(Point, usize) = undefined;

pub fn dfs_trace_beam(board: std.ArrayList(u8), w: usize, h: usize, p: Point) !usize {
    if (p.y == h - 1) {
        return 1;
    } else {
        if (dp.contains(p)) {
            return dp.get(p).?;
        }
        if (board.items[(p.y + 1) * w + p.x] == '^') {
            const left = if (p.x > 0 and board.items[(p.y + 1) * w + p.x - 1] == '.') try dfs_trace_beam(board, w, h, .{
                .x = p.x - 1,
                .y = (p.y + 1),
            }) else 0;
            const right = if (p.x < w and board.items[(p.y + 1) * w + p.x + 1] == '.') try dfs_trace_beam(board, w, h, .{
                .x = p.x + 1,
                .y = (p.y + 1),
            }) else 0;
            const res = left + right;
            try dp.put(p, res);
        } else {
            const res = try dfs_trace_beam(board, w, h, .{
                .x = p.x,
                .y = (p.y + 1),
            });
            try dp.put(p, res);
        }
        return dp.get(p).?;
    }
}

pub fn bfs_trace_beam(allocator: std.mem.Allocator, board: std.ArrayList(u8), w: usize, h: usize, p: Point) !usize {
    var splits: usize = 0;
    var queue: std.ArrayList(Point) = std.ArrayList(Point).init(allocator);
    defer queue.deinit();
    try queue.append(p);
    while (queue.items.len > 0) {
        const curr_p = queue.orderedRemove(0);
        if (board.items[curr_p.y * w + curr_p.x] == '^') {
            if (curr_p.x > 0 and board.items[curr_p.y * w + curr_p.x - 1] == '.') {
                try queue.append(.{
                    .x = curr_p.x - 1,
                    .y = curr_p.y,
                });
            }
            if (curr_p.x < w and board.items[curr_p.y * w + curr_p.x + 1] == '.') {
                board.items[curr_p.y * w + curr_p.x + 1] = '|';
                try queue.append(.{
                    .x = curr_p.x + 1,
                    .y = curr_p.y,
                });
            }
        } else {
            if (board.items[curr_p.y * w + curr_p.x] != 'S') board.items[curr_p.y * w + curr_p.x] = '|';
            if (curr_p.y + 1 < h) {
                try queue.append(.{
                    .x = curr_p.x,
                    .y = curr_p.y + 1,
                });
            }
        }
    }
    for (0..h) |i| {
        for (0..w) |j| {
            if (board.items[i * w + j] == '^' and board.items[(i - 1) * w + j] == '|') splits += 1;
        }
    }
    return splits;
}

pub fn print_board(board: std.ArrayList(u8), w: usize, h: usize) void {
    for (0..h) |i| {
        for (0..w) |j| {
            std.debug.print("{c}", .{board.items[i * w + j]});
        }
        std.debug.print("\n", .{});
    }
    std.debug.print("\n", .{});
}

pub fn day7_p1(self: anytype) !void {
    const f = try std.fs.cwd().openFile("inputs/day7/input.txt", .{});
    defer f.close();
    var buf: [65536]u8 = undefined;
    var board: std.ArrayList(u8) = std.ArrayList(u8).init(self.allocator);
    var w: usize = 0;
    var h: usize = 0;
    var start_point: usize = 0;
    defer board.deinit();
    while (try f.reader().readUntilDelimiterOrEof(&buf, '\n')) |unfiltered| {
        var line = unfiltered;
        if (std.mem.indexOfScalar(u8, unfiltered, '\r')) |indx| {
            line = unfiltered[0..indx];
        }
        if (line.len == 0) continue;
        if (std.mem.indexOfScalar(u8, line, 'S')) |indx| {
            start_point = indx;
        }
        for (line) |c| {
            try board.append(c);
        }
        h += 1;
        w = line.len;
    }
    //print_board(board, w, h);
    // const splits = dfs_trace_beam(board, w, h, .{
    //     .x = start_point,
    //     .y = 0,
    // });
    const splits = try bfs_trace_beam(self.allocator, board, w, h, .{
        .x = start_point,
        .y = 0,
    });
    //print_board(board, w, h);
    std.debug.print("Beam split {d} times.\n", .{splits});
}
