const std = @import("std");
// https://adventofcode.com/2024/day/22
// --- Day 22: Monkey Market ---
// As you're all teleported deep into the jungle, a monkey steals The Historians' device! You'll need get it back while The Historians are looking for the Chief.

// The monkey that stole the device seems willing to trade it, but only in exchange for an absurd number of bananas. Your only option is to buy bananas on the Monkey Exchange Market.

// You aren't sure how the Monkey Exchange Market works, but one of The Historians senses trouble and comes over to help. Apparently, they've been studying these monkeys for a while and have deciphered their secrets.

// Today, the Market is full of monkeys buying good hiding spots. Fortunately, because of the time you recently spent in this jungle, you know lots of good hiding spots you can sell! If you sell enough hiding spots, you should be able to get enough bananas to buy the device back.

// On the Market, the buyers seem to use random prices, but their prices are actually only pseudorandom! If you know the secret of how they pick their prices, you can wait for the perfect time to sell.

// The part about secrets is literal, the Historian explains. Each buyer produces a pseudorandom sequence of secret numbers where each secret is derived from the previous.

// In particular, each buyer's secret number evolves into the next secret number in the sequence via the following process:

// Calculate the result of multiplying the secret number by 64. Then, mix this result into the secret number. Finally, prune the secret number.
// Calculate the result of dividing the secret number by 32. Round the result down to the nearest integer. Then, mix this result into the secret number. Finally, prune the secret number.
// Calculate the result of multiplying the secret number by 2048. Then, mix this result into the secret number. Finally, prune the secret number.
// Each step of the above process involves mixing and pruning:

// To mix a value into the secret number, calculate the bitwise XOR of the given value and the secret number. Then, the secret number becomes the result of that operation. (If the secret number is 42 and you were to mix 15 into the secret number, the secret number would become 37.)
// To prune the secret number, calculate the value of the secret number modulo 16777216. Then, the secret number becomes the result of that operation. (If the secret number is 100000000 and you were to prune the secret number, the secret number would become 16113920.)
// After this process completes, the buyer is left with the next secret number in the sequence. The buyer can repeat this process as many times as necessary to produce more secret numbers.

// So, if a buyer had a secret number of 123, that buyer's next ten secret numbers would be:

// 15887950
// 16495136
// 527345
// 704524
// 1553684
// 12683156
// 11100544
// 12249484
// 7753432
// 5908254
// Each buyer uses their own secret number when choosing their price, so it's important to be able to predict the sequence of secret numbers for each buyer. Fortunately, the Historian's research has uncovered the initial secret number of each buyer (your puzzle input). For example:

// 1
// 10
// 100
// 2024
// This list describes the initial secret number of four different secret-hiding-spot-buyers on the Monkey Exchange Market. If you can simulate secret numbers from each buyer, you'll be able to predict all of their future prices.

// In a single day, buyers each have time to generate 2000 new secret numbers. In this example, for each buyer, their initial secret number and the 2000th new secret number they would generate are:

// 1: 8685429
// 10: 4700978
// 100: 15273692
// 2024: 8667524
// Adding up the 2000th new secret number for each buyer produces 37327623.

// For each buyer, simulate the creation of 2000 new secret numbers. What is the sum of the 2000th secret number generated by each buyer?

const colors = .{
    .red = "\x1B[91m",
    .green = "\x1B[92m",
    .yellow = "\x1B[93m",
    .blue = "\x1B[94m",
    .magenta = "\x1B[95m",
    .cyan = "\x1B[96m",
    .dark_red = "\x1B[31m",
    .dark_green = "\x1B[32m",
    .dark_yellow = "\x1B[33m",
    .dark_blue = "\x1B[34m",
    .dark_magenta = "\x1B[35m",
    .dark_cyan = "\x1B[36m",
    .white = "\x1B[37m",
    .end = "\x1B[0m",
};

//ansi escape codes
const esc = "\x1B";
const csi = esc ++ "[";

const cursor_show = csi ++ "?25h"; //h=high
const cursor_hide = csi ++ "?25l"; //l=low
const cursor_home = csi ++ "1;1H"; //1,1

const color_fg = "38;5;";
const color_bg = "48;5;";
const color_fg_def = csi ++ color_fg ++ "15m"; // white
const color_bg_def = csi ++ color_bg ++ "0m"; // black
const color_def = color_bg_def ++ color_fg_def;

const screen_clear = csi ++ "2J";
const screen_buf_on = csi ++ "?1049h"; //h=high
const screen_buf_off = csi ++ "?1049l"; //l=low

const nl = "\n";

const term_on = screen_buf_on ++ cursor_hide ++ cursor_home ++ screen_clear ++ color_def;
const term_off = screen_buf_off ++ cursor_show ++ nl;
var num_buf: [4096]u8 = undefined;
var scratch_str: std.ArrayList(u8) = undefined;
const DEBUG = false;

pub fn mix(secret_number: i64, mixin: i64) i64 {
    return secret_number ^ mixin;
}

pub fn prune(secret_number: i64) i64 {
    return @mod(secret_number, 16777216);
}

pub fn evolve(secret_number: i64, generations: u64) i64 {
    var new_secret_number = secret_number;
    for (0..generations) |_| {
        const mul_64 = new_secret_number * 64;
        new_secret_number = prune(mix(new_secret_number, mul_64));

        const div_32 = @divFloor(new_secret_number, 32);
        new_secret_number = prune(mix(new_secret_number, div_32));

        const mul_2048 = new_secret_number * 2048;
        new_secret_number = prune(mix(new_secret_number, mul_2048));
    }
    return new_secret_number;
}

pub fn evolve_differences(secret_number: i64, differences: []i64, banana_map: *std.AutoHashMap(BananaKey, i64), generations: u64) !i64 {
    var new_secret_number = secret_number;
    for (0..generations) |i| {
        const previous_secret_number = new_secret_number;
        const mul_64 = new_secret_number * 64;
        new_secret_number = prune(mix(new_secret_number, mul_64));

        const div_32 = @divFloor(new_secret_number, 32);
        new_secret_number = prune(mix(new_secret_number, div_32));

        const mul_2048 = new_secret_number * 2048;
        new_secret_number = prune(mix(new_secret_number, mul_2048));
        //std.debug.print("{d}({d}) - {d}({d}) = {d}\n", .{ new_secret_number, @mod(new_secret_number, 10), previous_secret_number, @mod(previous_secret_number, 10), @mod(new_secret_number, 10) - @mod(previous_secret_number, 10) });
        differences[i] = @mod(new_secret_number, 10) - @mod(previous_secret_number, 10);
        if (i >= 3) {
            const price = @mod(new_secret_number, 10);
            const key = BananaKey{
                .a = differences[i],
                .b = differences[i - 1],
                .c = differences[i - 2],
                .d = differences[i - 3],
            };
            const entry = try banana_map.getOrPut(key);
            if (!entry.found_existing) {
                entry.value_ptr.* = price;
            }
            //std.debug.print("Adding {any} with value {d}\n", .{ key, price });
        }
    }
    return new_secret_number;
}

pub fn part1(file_name: []const u8, allocator: std.mem.Allocator) !i64 {
    const f = try std.fs.cwd().openFile(file_name, .{});
    defer f.close();
    var buf: [65536]u8 = undefined;
    var starting_numbers = std.ArrayList(i64).init(allocator);
    defer starting_numbers.deinit();
    while (try f.reader().readUntilDelimiterOrEof(&buf, '\n')) |unfiltered| {
        var line = unfiltered;
        if (std.mem.indexOfScalar(u8, unfiltered, '\r')) |indx| {
            line = unfiltered[0..indx];
        }
        if (line.len == 0) continue;
        try starting_numbers.append(try std.fmt.parseInt(i64, line, 10));
    }
    var total: i64 = 0;
    //td.debug.print("Starting numbers: {any}\n", .{starting_numbers.items});
    for (0..starting_numbers.items.len) |i| {
        const new_number = evolve(starting_numbers.items[i], 2000);
        //std.debug.print("{d}: {d}\n", .{ starting_numbers.items[i], new_number });
        total += new_number;
    }

    return total;
}

// --- Part Two ---
// Of course, the secret numbers aren't the prices each buyer is offering! That would be ridiculous. Instead, the prices the buyer offers are just the ones digit of each of their secret numbers.

// So, if a buyer starts with a secret number of 123, that buyer's first ten prices would be:

// 3 (from 123)
// 0 (from 15887950)
// 6 (from 16495136)
// 5 (etc.)
// 4
// 4
// 6
// 4
// 4
// 2
// This price is the number of bananas that buyer is offering in exchange for your information about a new hiding spot. However, you still don't speak monkey, so you can't negotiate with the buyers directly. The Historian speaks a little, but not enough to negotiate; instead, he can ask another monkey to negotiate on your behalf.

// Unfortunately, the monkey only knows how to decide when to sell by looking at the changes in price. Specifically, the monkey will only look for a specific sequence of four consecutive changes in price, then immediately sell when it sees that sequence.

// So, if a buyer starts with a secret number of 123, that buyer's first ten secret numbers, prices, and the associated changes would be:

//      123: 3
// 15887950: 0 (-3)
// 16495136: 6 (6)
//   527345: 5 (-1)
//   704524: 4 (-1)
//  1553684: 4 (0)
// 12683156: 6 (2)
// 11100544: 4 (-2)
// 12249484: 4 (0)
//  7753432: 2 (-2)
// Note that the first price has no associated change because there was no previous price to compare it with.

// In this short example, within just these first few prices, the highest price will be 6, so it would be nice to give the monkey instructions that would make it sell at that time. The first 6 occurs after only two changes, so there's no way to instruct the monkey to sell then, but the second 6 occurs after the changes -1,-1,0,2. So, if you gave the monkey that sequence of changes, it would wait until the first time it sees that sequence and then immediately sell your hiding spot information at the current price, winning you 6 bananas.

// Each buyer only wants to buy one hiding spot, so after the hiding spot is sold, the monkey will move on to the next buyer. If the monkey never hears that sequence of price changes from a buyer, the monkey will never sell, and will instead just move on to the next buyer.

// Worse, you can only give the monkey a single sequence of four price changes to look for. You can't change the sequence between buyers.

// You're going to need as many bananas as possible, so you'll need to determine which sequence of four price changes will cause the monkey to get you the most bananas overall. Each buyer is going to generate 2000 secret numbers after their initial secret number, so, for each buyer, you'll have 2000 price changes in which your sequence can occur.

// Suppose the initial secret number of each buyer is:

// 1
// 2
// 3
// 2024
// There are many sequences of four price changes you could tell the monkey, but for these four buyers, the sequence that will get you the most bananas is -2,1,-1,3. Using that sequence, the monkey will make the following sales:

// For the buyer with an initial secret number of 1, changes -2,1,-1,3 first occur when the price is 7.
// For the buyer with initial secret 2, changes -2,1,-1,3 first occur when the price is 7.
// For the buyer with initial secret 3, the change sequence -2,1,-1,3 does not occur in the first 2000 changes.
// For the buyer starting with 2024, changes -2,1,-1,3 first occur when the price is 9.
// So, by asking the monkey to sell the first time each buyer's prices go down 2, then up 1, then down 1, then up 3, you would get 23 (7 + 7 + 9) bananas!

// Figure out the best sequence to tell the monkey so that by looking for that same sequence of changes in every buyer's future prices, you get the most bananas in total. What is the most bananas you can get?

pub const BananaKey = struct {
    a: i64,
    b: i64,
    c: i64,
    d: i64,
};

pub fn part2(file_name: []const u8, allocator: std.mem.Allocator) !i64 {
    const f = try std.fs.cwd().openFile(file_name, .{});
    defer f.close();
    var buf: [65536]u8 = undefined;
    var starting_numbers = std.ArrayList(i64).init(allocator);
    defer starting_numbers.deinit();
    while (try f.reader().readUntilDelimiterOrEof(&buf, '\n')) |unfiltered| {
        var line = unfiltered;
        if (std.mem.indexOfScalar(u8, unfiltered, '\r')) |indx| {
            line = unfiltered[0..indx];
        }
        if (line.len == 0) continue;
        try starting_numbers.append(try std.fmt.parseInt(i64, line, 10));
    }
    var total: i64 = 0;
    //std.debug.print("Starting numbers: {any}\n", .{starting_numbers.items});
    var differences = std.ArrayList([]i64).init(allocator);
    defer differences.deinit();
    var banana_maps = std.ArrayList(std.AutoHashMap(BananaKey, i64)).init(allocator);
    defer banana_maps.deinit();
    for (0..starting_numbers.items.len) |i| {
        try differences.append(try allocator.alloc(i64, 2000));
        try banana_maps.append(std.AutoHashMap(BananaKey, i64).init(allocator));
        _ = try evolve_differences(starting_numbers.items[i], differences.items[i], &banana_maps.items[i], 2000);
        //std.debug.print("{d}: {d}\n", .{ starting_numbers.items[i], new_number });
    }

    for (1..banana_maps.items.len) |i| {
        var it = banana_maps.items[i].iterator();
        while (it.next()) |entry| {
            const total_entry = try banana_maps.items[0].getOrPut(entry.key_ptr.*);
            if (total_entry.found_existing) {
                total_entry.value_ptr.* += entry.value_ptr.*;
            } else {
                total_entry.value_ptr.* = entry.value_ptr.*;
            }
        }
    }
    var it = banana_maps.items[0].iterator();
    while (it.next()) |entry| {
        total = @max(total, entry.value_ptr.*);
    }
    for (0..differences.items.len) |i| {
        allocator.free(differences.items[i]);
    }
    for (0..banana_maps.items.len) |i| {
        banana_maps.items[i].deinit();
    }

    return total;
}

test "day22" {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();
    scratch_str = std.ArrayList(u8).init(allocator);
    var timer = try std.time.Timer.start();
    std.debug.print("Sum of 2000th secret number {d} in {d}ms\n", .{ try part1("../inputs/day22/input.txt", allocator), timer.lap() / std.time.ns_per_ms });
    std.debug.print("Most bananas you can get {d} in {d}ms\n", .{ try part2("../inputs/day22/input.txt", allocator), timer.lap() / std.time.ns_per_ms });
    scratch_str.deinit();
    if (gpa.deinit() == .leak) {
        std.debug.print("Leaked!\n", .{});
    }
}

// test "evolve 123" {
//     var secret_number = evolve(123, 1);
//     std.debug.print("123\n{d}\n", .{secret_number});
//     for (0..9) |_| {
//         secret_number = evolve(secret_number, 1);
//         std.debug.print("{d}\n", .{secret_number});
//     }
// }

// test "evolve differences 123" {
//     var gpa = std.heap.GeneralPurposeAllocator(.{}){};
//     const allocator = gpa.allocator();
//     const difference = try allocator.alloc(i64, 10);
//     var secret_number: i64 = 123;
//     std.debug.print("123: 3\n", .{});
//     secret_number = evolve_differences(secret_number, difference, 10);
//     for (0..10) |i| {
//         std.debug.print("({d})\n", .{difference[i]});
//     }
//     allocator.free(difference);
//     if (gpa.deinit() == .leak) {
//         std.debug.print("Leaked!\n", .{});
//     }
// }
